name: Python package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: pypy3
    - name: pypy absolute path
      run: C:\hostedtoolcache\windows\PyPy\3.6.9\x86\pypy3 -v
    - name: pypy in path
      run: pypy3 -v
    - name: Look for mingw
      run: gcc --version
