# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: pypy3
    - name: pypy absolute path
      run: |
        ls C:\hostedtoolcache\windows\PyPy
        ls C:\hostedtoolcache\windows\PyPy\3.6.9
        ls C:\hostedtoolcache\windows\PyPy\3.6.9\x86 
        ls C:\hostedtoolcache\windows\PyPy\3.6.9\x86\bin
#      C:\hostedtoolcache\windows\PyPy\3.6.9\x86\bin\pypy3 -v
    - name: pypy in path
      run: pypy3 -v
    - name: Look for mingw
      run: gcc --version
